version: '3.3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: R00t!
    ports:
      - '27017:27017'

  php-apache:
    container_name: app
    build:
      context: ./src
    environment:
      - APP_NAME=Birthday Book
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - APP_KEY=base64:3UBZXVVVX4AzMpQGDL1SVKket2bGAMHrSpglcIqhW54=
      - DB_CONNECTION=mongodb
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_DATABASE=bdbook
      - DB_USERNAME=root
      - DB_PASSWORD=R00t!
    ports:
        - '8080:80'
    volumes:
      - ./src:/app
    depends_on:
      - mongo